/**
 * Lucide → Phosphor icon name map.
 *
 * Consumed by scripts/codemod-lucide-to-phosphor.mjs to rewrite imports
 * across the codebase. Keys are Lucide component names as they appear in
 * `import { X } from 'lucide-react'`. Values are the Phosphor component
 * name. The codemod aliases to preserve the original local identifier,
 * so JSX call sites (`<Heart />`, `<MessageCircle />`) don't change.
 *
 * Any Lucide icon not in this map is left untouched by the codemod and
 * surfaces as a warning in the dry-run report; add it here to include it.
 *
 * Verify any additions with `npx vitest run tests/brand/iconMap.test.ts`.
 */
export const ICON_MAP = {
  AlertCircle: 'WarningCircle',
  AlertTriangle: 'Warning',
  Archive: 'Archive',
  ArrowLeft: 'ArrowLeft',
  ArrowRight: 'ArrowRight',
  ArrowUp: 'ArrowUp',
  ArrowUpDown: 'ArrowsDownUp',
  AtSign: 'At',
  Award: 'Medal',
  Baby: 'Baby',
  BarChart3: 'ChartBar',
  Bell: 'Bell',
  Bitcoin: 'CurrencyBtc',
  Brain: 'Brain',
  Building2: 'Buildings',
  Bus: 'Bus',
  Calendar: 'Calendar',
  CalendarDays: 'CalendarDots',
  CalendarRange: 'CalendarBlank',
  Camera: 'Camera',
  Captions: 'ClosedCaptioning',
  Car: 'Car',
  Cat: 'Cat',
  Check: 'Check',
  CheckCircle: 'CheckCircle',
  CheckCircle2: 'CheckCircle',
  ChefHat: 'ChefHat',
  ChevronDown: 'CaretDown',
  ChevronLeft: 'CaretLeft',
  ChevronRight: 'CaretRight',
  ChevronUp: 'CaretUp',
  Circle: 'Circle',
  CircleDot: 'Record',
  CircleHelp: 'Question',
  Clapperboard: 'FilmSlate',
  Clock: 'Clock',
  Cloud: 'Cloud',
  CloudOff: 'CloudSlash',
  Code: 'Code',
  Code2: 'Code',
  Coffee: 'Coffee',
  Compass: 'Compass',
  Copy: 'Copy',
  CornerDownRight: 'ArrowBendDownRight',
  Cpu: 'Cpu',
  DollarSign: 'CurrencyDollar',
  Dot: 'Dot',
  Download: 'DownloadSimple',
  Drama: 'SmileyMelting',
  Dumbbell: 'Barbell',
  Edit: 'PencilSimple',
  ExternalLink: 'ArrowSquareOut',
  Eye: 'Eye',
  FileText: 'FileText',
  Film: 'FilmStrip',
  Fingerprint: 'Fingerprint',
  Flag: 'Flag',
  Flame: 'Flame',
  Gamepad2: 'GameController',
  Github: 'GithubLogo',
  Globe: 'Globe',
  GraduationCap: 'GraduationCap',
  Grid: 'SquaresFour',
  Grid3X3: 'GridFour',
  GripVertical: 'DotsSixVertical',
  Hash: 'Hash',
  Headphones: 'Headphones',
  Heart: 'Heart',
  HelpCircle: 'Question',
  Home: 'House',
  Infinity: 'Infinity',
  Info: 'Info',
  Key: 'Key',
  KeyRound: 'Key',
  Landmark: 'Bank',
  Languages: 'Translate',
  Laugh: 'SmileyWink',
  LayoutGrid: 'SquaresFour',
  LifeBuoy: 'Lifebuoy',
  Link2: 'LinkSimple',
  List: 'List',
  ListPlus: 'ListPlus',
  Loader2: 'CircleNotch',
  Lock: 'Lock',
  LogIn: 'SignIn',
  LogOut: 'SignOut',
  Mail: 'Envelope',
  MapPin: 'MapPin',
  Maximize2: 'ArrowsOutSimple',
  MessageCircle: 'ChatCircle',
  MessageSquare: 'Chat',
  Moon: 'Moon',
  MoreHorizontal: 'DotsThree',
  MoreVertical: 'DotsThreeVertical',
  Music: 'MusicNote',
  Newspaper: 'Newspaper',
  Palette: 'Palette',
  PanelLeft: 'SidebarSimple',
  PartyPopper: 'Confetti',
  PawPrint: 'PawPrint',
  Pencil: 'PencilSimple',
  Pin: 'PushPin',
  PinOff: 'PushPinSlash',
  Plane: 'AirplaneTilt',
  Play: 'Play',
  Plus: 'Plus',
  RefreshCw: 'ArrowsClockwise',
  Repeat: 'Repeat',
  Repeat2: 'Repeat',
  Rocket: 'Rocket',
  Rss: 'Rss',
  Save: 'FloppyDisk',
  Scale: 'Scales',
  Scissors: 'Scissors',
  Search: 'MagnifyingGlass',
  Send: 'PaperPlaneTilt',
  Settings: 'Gear',
  Share: 'Share',
  Share2: 'ShareNetwork',
  Shield: 'Shield',
  ShieldAlert: 'ShieldWarning',
  ShieldCheck: 'ShieldCheck',
  ShieldQuestion: 'ShieldCheck',
  Shirt: 'TShirt',
  ShoppingBag: 'ShoppingBag',
  Shuffle: 'Shuffle',
  Smartphone: 'DeviceMobile',
  Smile: 'Smiley',
  Sofa: 'Couch',
  Sparkle: 'Sparkle',
  Sparkles: 'Sparkle',
  Sprout: 'Plant',
  Star: 'Star',
  Sun: 'Sun',
  Tag: 'Tag',
  Trash2: 'Trash',
  TreePine: 'TreeEvergreen',
  TrendingUp: 'TrendUp',
  TriangleAlert: 'Warning',
  Trophy: 'Trophy',
  Tv: 'Television',
  Type: 'TextAa',
  Upload: 'UploadSimple',
  User: 'User',
  // UserIcon is a Lucide alias variant of User — same Phosphor target.
  UserIcon: 'User',
  UserCheck: 'UserCheck',
  UserPlus: 'UserPlus',
  UserX: 'UserMinus',
  Users: 'Users',
  UtensilsCrossed: 'ForkKnife',
  Video: 'VideoCamera',
  Volume2: 'SpeakerHigh',
  VolumeX: 'SpeakerX',
  Wallet: 'Wallet',
  WalletMinimal: 'Wallet',
  Wrench: 'Wrench',
  X: 'X',
  XCircle: 'XCircle',
  Zap: 'Lightning',
} as const;

export type LucideName = keyof typeof ICON_MAP;
